import React, { Component } from 'react';
import Stripe from './Stripe';
import bitcoin from '../../images/bitcoin.png';
import ethereum from '../../images/ethereum.png';
import litecoin from '../../images/litecoin.png';

class Donate extends Component {
  constructor() {
    super();

    this.state = {
      amount: 0
    };
  }

  handleInput(val) {
    this.setState({
      amount: val
    });
  }

  render() {
    return (
      <div>
        <div className="page-welcome">
          {' '}
          <span className="page-number">04</span> Donate
        </div>

        <div className="container text-left donate-title-1 page-donate">
          <h2 className="mb-3">Donate to DOM Leaks</h2>
          <div className="white-line mb-4" />
          <p>
            <span className="mr-1 dash">/ </span> DOM Leaks is entirely
            supported by the general public.
          </p>
          <p>
            <span className="mr-1 dash">/ </span>
            Your donations pay for DOM Leaks projects, staff, servers and
            protective infrastructure.
          </p>
        </div>

        <div className="account-info container">
          <div className="card bg-light text-dark donate-card">
            <div className="card-header">
              <h4 className="donate text-left">Credit Card</h4>
            </div>
            <div className="card-body">
              <p className="donate-text text-left">
                Global credit card donations via stripe
              </p>
              <p className="donate-text text-left p-1 text-primary">
                Donations made via stripe are tax deductible in the EU.
              </p>
            </div>
            <div className="card-footer">
              <input
                type="text"
                placeholder="0.00"
                className="stripe-input mr-3 mb-4 bg-light"
                onChange={e => this.handleInput(e.target.value)}
              />
              <p className="stripe-price d-inline">USD</p>
              <Stripe amount={this.state.amount} />
            </div>
          </div>
        </div>

        <div className="account-info container">
          <div className="card bg-light text-dark donate-card">
            <div className="card-header">
              <h4 className="donate text-left">Bitcoin</h4>
            </div>
            <div className="card-body">
              <p className="donate-text text-left">
                Bitcoin is a secure and anonymous digital currency. Bitcoins
                cannot be easily tracked back to you, and are safer and faster
                alternative to other donation methods. You can send BTC to the
                following address:
              </p>
              <p className="donate-text text-left p-1 text-danger">
                3M4rvRqbkaCfudp7bXLNE62d1iBL2wYVNA
              </p>
            </div>
            <div className="card-footer">
              <button
                data-toggle="modal"
                data-target="#bitcoinModal"
                className="donate-btn float-left"
              >
                QR Code
              </button>
            </div>
          </div>
        </div>

        <div className="account-info container">
          <div className="card bg-light text-dark donate-card">
            <div className="card-header">
              <h4 className="donate text-left">Ethereum</h4>
            </div>
            <div className="card-body">
              <p className="donate-text text-left">
                Ether is a cryptocurrency whose blockchain is generated by the
                Ethereum platform. Ethereum is a decentralized platform that
                runs smart contracts: applications that run exactly as
                programmed, without any possibility of downtime, censorship,
                fraud or third-party interference. You can donate to us using
                the address below:
              </p>
              <p className="donate-text text-left p-1 text-danger">
                0x4B7F16a7e92033a07c6E985E234BAeeBB6EE3E41
              </p>
            </div>
            <div className="card-footer">
              <button
                data-toggle="modal"
                data-target="#ethereumModal"
                className="donate-btn float-left"
              >
                QR Code
              </button>
            </div>
          </div>
        </div>

        <div className="account-info container mb-5">
          <div className="card bg-light text-dark donate-card">
            <div className="card-header">
              <h4 className="donate text-left">Litecoin</h4>
            </div>
            <div className="card-body">
              <p className="donate-text text-left">
                Simillar to Bitcoin, Litecoin offers very fast and secure
                transactions worldwide, and there are many exchanges allowing
                you to trade for Litecoins. Litecoin users may choose to donate
                to us at:
              </p>
              <p className="donate-text text-left p-1 text-danger">
                MHKrZqfGoSfitRzgEFrpQx8qi7R2UBaNxA
              </p>
            </div>
            <div className="card-footer">
              <button
                data-toggle="modal"
                data-target="#litecoinModal"
                className="donate-btn float-left"
              >
                QR Code
              </button>
            </div>
          </div>
        </div>

        <div
          className="modal fade"
          id="bitcoinModal"
          role="dialog"
          aria-labelledby="bitcoinModal"
          aria-hidden="true"
        >
          <div className="modal-dialog" role="document">
            <div className="modal-content">
              <div className="card-header">
                <button
                  type="button"
                  className="close ml-auto"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div className="modal-body">
                <img width="200px" src={bitcoin} alt="" />
              </div>
              <div className="modal-footer">
                <button
                  type="button"
                  className="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>

        <div
          className="modal fade"
          id="ethereumModal"
          role="dialog"
          aria-labelledby="ethereumModal"
          aria-hidden="true"
        >
          <div className="modal-dialog" role="document">
            <div className="modal-content">
              <div className="card-header">
                <button
                  type="button"
                  className="close ml-auto"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div className="modal-body">
                <img width="200px" src={ethereum} alt="" />
              </div>
              <div className="modal-footer">
                <button
                  type="button"
                  className="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>

        <div
          className="modal fade"
          id="litecoinModal"
          role="dialog"
          aria-labelledby="litecoinModal"
          aria-hidden="true"
        >
          <div className="modal-dialog" role="document">
            <div className="modal-content">
              <div className="card-header">
                <button
                  type="button"
                  className="close ml-auto"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div className="modal-body">
                <img width="200px" src={litecoin} alt="" />
              </div>
              <div className="modal-footer">
                <button
                  type="button"
                  className="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Donate;
